name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      nightly_validation:
        description: "Validate a nightly candidate"
        type: boolean
        required: false
        default: false

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install stable tooling Roc and latest nightly
        id: roc
        uses: lukewilliamboswell/setup-roc@89a8a2945bd107f27b160096b3af7f52d2d78369
        with:
          version: stable-and-nightly
      - run: roc-nightly version
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install --yes pandoc
      - run: pandoc --version
      - run: scripts/check_all.roc
        env:
          ROC_STABLE: ${{ steps.roc.outputs.stable-executable }}
          ROC_NIGHTLY: ${{ steps.roc.outputs.nightly-executable }}
