name: Nightly configuration

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  configuration:
    uses: lukewilliamboswell/roc-automation/.github/workflows/check-config.yml@3937ff6a0fff8926ca0b8449d2555274cfccff0a
